# Copyright (c) 2017, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

sudo: required

env: 
  global: 
    - COVERALLS_PARALLEL=true

services:
  - docker

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.9.0
  - nvm use 8.9.0
  - npm install -g npm@'5.6.0'
  - mvn clean install -B -V -Dvscode.test.skip=true -Dcheckstyle.skip -Dfindbugs.skip=true -Dspotbugs.skip=true

script: echo "Done"

notifications:
  webhooks: https://coveralls.io/webhook

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
  - composer/modules/web/node_modules
  - tool-plugins/vscode/node_modules