jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 150
  variables:
    GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - script: |
      sudo ulimit -n 65535
      wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      tar xzf apache-maven-3.5.4-bin.tar.gz
      export PATH=$(pwd)/apache-maven-3.5.4/bin:$PATH
      mvn -v
      mvn clean install
    displayName: 'Ballerina Linux Build'
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 150
  variables:
    GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - task: CacheBeta@0
    inputs:
      key: gradle | $(Agent.OS)
      path: $(GRADLE_USER_HOME)
    displayName: Gradle build cache
  - script: |
      ./gradlew build -Dorg.gradle.parallel=false -x :language-server:language-server-core:test -x :ballerina-packerina:test -x :ballerina-lang:test -x :ballerina-http:test -x :ballerina-file:test -x :ballerina-task:test -x :ballerina-socket:test -x :jballerina-unit-test:test -x :jballerina-integration-test:test -x :plugin-vscode:test -x createJavadoc --stacktrace -scan --console=plain --no-daemon
    displayName: 'Ballerina Windows Build'