jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 150
  variables:
    GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - script: |
      sudo ulimit -n 65535
      wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      tar xzf apache-maven-3.5.4-bin.tar.gz
      export PATH=$(pwd)/apache-maven-3.5.4/bin:$PATH
      mvn -v
      mvn clean install
    displayName: 'Ballerina Linux Build'
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  timeoutInMinutes: 150
  variables:
    GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
  - script: |
      mvn -v
      ./gradlew build
    displayName: 'Ballerina Windows Build'